### get all persons
GET http://localhost:3001/api/persons/

### get 1 person
GET http://localhost:3001/api/persons/634d28a2d1a4492f0b4c4b77

### delete person
DELETE http://localhost:3001/api/persons/634d2938c008f7d4ebedf4f4

### add person
POST http://localhost:3001/api/persons/ HTTP/3
content-type: application/json

{
    "name": "aaa",
    "number": "01-2345678"
}

### update person
PUT http://localhost:3001/api/persons/634d2938c008f7d4ebedf4f4
content-type: application/json

{
    "name": "aaa",
    "number": "12-345678"
}